//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Hotkeys : global::System.Configuration.ApplicationSettingsBase {
        
        private static Hotkeys defaultInstance = ((Hotkeys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Hotkeys())));
        
        public static Hotkeys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string AGL_Altitude {
            get {
                return ((string)(this["AGL_Altitude"]));
            }
            set {
                this["AGL_Altitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OemCloseBrackets")]
        public string Command_Key {
            get {
                return ((string)(this["Command_Key"]));
            }
            set {
                this["Command_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string ASL_Altitude {
            get {
                return ((string)(this["ASL_Altitude"]));
            }
            set {
                this["ASL_Altitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public string Aircraft_Heading {
            get {
                return ((string)(this["Aircraft_Heading"]));
            }
            set {
                this["Aircraft_Heading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string Indicated_Airspeed {
            get {
                return ((string)(this["Indicated_Airspeed"]));
            }
            set {
                this["Indicated_Airspeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string True_Airspeed {
            get {
                return ((string)(this["True_Airspeed"]));
            }
            set {
                this["True_Airspeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string Mach_Speed {
            get {
                return ((string)(this["Mach_Speed"]));
            }
            set {
                this["Mach_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public string Vertical_Speed {
            get {
                return ((string)(this["Vertical_Speed"]));
            }
            set {
                this["Vertical_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("O")]
        public string Outside_Temperature {
            get {
                return ((string)(this["Outside_Temperature"]));
            }
            set {
                this["Outside_Temperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+T")]
        public string Toggle_Trim_Announcement {
            get {
                return ((string)(this["Toggle_Trim_Announcement"]));
            }
            set {
                this["Toggle_Trim_Announcement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+R")]
        public string Mute_Simconnect_Messages {
            get {
                return ((string)(this["Mute_Simconnect_Messages"]));
            }
            set {
                this["Mute_Simconnect_Messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string Nearest_City {
            get {
                return ((string)(this["Nearest_City"]));
            }
            set {
                this["Nearest_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public string Next_Waypoint {
            get {
                return ((string)(this["Next_Waypoint"]));
            }
            set {
                this["Next_Waypoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string Destination_Info {
            get {
                return ((string)(this["Destination_Info"]));
            }
            set {
                this["Destination_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OemOpenBrackets")]
        public string Attitude_Mode {
            get {
                return ((string)(this["Attitude_Mode"]));
            }
            set {
                this["Attitude_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+M")]
        public string Speak_Attitude {
            get {
                return ((string)(this["Speak_Attitude"]));
            }
            set {
                this["Speak_Attitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+A")]
        public string Toggle_Autopilot_Announcement {
            get {
                return ((string)(this["Toggle_Autopilot_Announcement"]));
            }
            set {
                this["Toggle_Autopilot_Announcement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+G")]
        public string Toggle_GPWS_Announcement {
            get {
                return ((string)(this["Toggle_GPWS_Announcement"]));
            }
            set {
                this["Toggle_GPWS_Announcement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+I")]
        public string Toggle_ILS_Announcement {
            get {
                return ((string)(this["Toggle_ILS_Announcement"]));
            }
            set {
                this["Toggle_ILS_Announcement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F")]
        public string Toggle_Flaps_Announcement {
            get {
                return ((string)(this["Toggle_Flaps_Announcement"]));
            }
            set {
                this["Toggle_Flaps_Announcement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I")]
        public string Wind_Information {
            get {
                return ((string)(this["Wind_Information"]));
            }
            set {
                this["Wind_Information"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+H")]
        public string Runway_Guidance_Mode {
            get {
                return ((string)(this["Runway_Guidance_Mode"]));
            }
            set {
                this["Runway_Guidance_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public string Fuel_Report {
            get {
                return ((string)(this["Fuel_Report"]));
            }
            set {
                this["Fuel_Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string Fuel_Flow {
            get {
                return ((string)(this["Fuel_Flow"]));
            }
            set {
                this["Fuel_Flow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Fuel_Tank_1 {
            get {
                return ((string)(this["Fuel_Tank_1"]));
            }
            set {
                this["Fuel_Tank_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string Fuel_Tank_2 {
            get {
                return ((string)(this["Fuel_Tank_2"]));
            }
            set {
                this["Fuel_Tank_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string Fuel_Tank_3 {
            get {
                return ((string)(this["Fuel_Tank_3"]));
            }
            set {
                this["Fuel_Tank_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string Fuel_Tank_4 {
            get {
                return ((string)(this["Fuel_Tank_4"]));
            }
            set {
                this["Fuel_Tank_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string Fuel_Tank_5 {
            get {
                return ((string)(this["Fuel_Tank_5"]));
            }
            set {
                this["Fuel_Tank_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string Fuel_Tank_6 {
            get {
                return ((string)(this["Fuel_Tank_6"]));
            }
            set {
                this["Fuel_Tank_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string Fuel_Tank_7 {
            get {
                return ((string)(this["Fuel_Tank_7"]));
            }
            set {
                this["Fuel_Tank_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string Fuel_Tank_8 {
            get {
                return ((string)(this["Fuel_Tank_8"]));
            }
            set {
                this["Fuel_Tank_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string Fuel_Tank_9 {
            get {
                return ((string)(this["Fuel_Tank_9"]));
            }
            set {
                this["Fuel_Tank_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Fuel_Tank_10 {
            get {
                return ((string)(this["Fuel_Tank_10"]));
            }
            set {
                this["Fuel_Tank_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public string Nearby_Airborn_Aircraft {
            get {
                return ((string)(this["Nearby_Airborn_Aircraft"]));
            }
            set {
                this["Nearby_Airborn_Aircraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+P")]
        public string Nearby_Ground_Aircraft {
            get {
                return ((string)(this["Nearby_Ground_Aircraft"]));
            }
            set {
                this["Nearby_Ground_Aircraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+1")]
        public string Engine_1_Info {
            get {
                return ((string)(this["Engine_1_Info"]));
            }
            set {
                this["Engine_1_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+2")]
        public string Engine_2_Info {
            get {
                return ((string)(this["Engine_2_Info"]));
            }
            set {
                this["Engine_2_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+3")]
        public string Engine_3_Info {
            get {
                return ((string)(this["Engine_3_Info"]));
            }
            set {
                this["Engine_3_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+4")]
        public string Engine_4_Info {
            get {
                return ((string)(this["Engine_4_Info"]));
            }
            set {
                this["Engine_4_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+W")]
        public string Weight_Report {
            get {
                return ((string)(this["Weight_Report"]));
            }
            set {
                this["Weight_Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public string Repeat_Last_Simconnect_Message {
            get {
                return ((string)(this["Repeat_Last_Simconnect_Message"]));
            }
            set {
                this["Repeat_Last_Simconnect_Message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string Read_Simulation_Rate {
            get {
                return ((string)(this["Read_Simulation_Rate"]));
            }
            set {
                this["Read_Simulation_Rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public string Ground_Speed {
            get {
                return ((string)(this["Ground_Speed"]));
            }
            set {
                this["Ground_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+1")]
        public string Engine_1_Throttle {
            get {
                return ((string)(this["Engine_1_Throttle"]));
            }
            set {
                this["Engine_1_Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+2")]
        public string Engine_2_Throttle {
            get {
                return ((string)(this["Engine_2_Throttle"]));
            }
            set {
                this["Engine_2_Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+3")]
        public string Engine_3_Throttle {
            get {
                return ((string)(this["Engine_3_Throttle"]));
            }
            set {
                this["Engine_3_Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+4")]
        public string Engine_4_Throttle {
            get {
                return ((string)(this["Engine_4_Throttle"]));
            }
            set {
                this["Engine_4_Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+C")]
        public string Current_Location {
            get {
                return ((string)(this["Current_Location"]));
            }
            set {
                this["Current_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public string Disable_Command_Key {
            get {
                return ((string)(this["Disable_Command_Key"]));
            }
            set {
                this["Disable_Command_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+B")]
        public string Toggle_Braille_output {
            get {
                return ((string)(this["Toggle_Braille_output"]));
            }
            set {
                this["Toggle_Braille_output"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string ap_Get_Altitude {
            get {
                return ((string)(this["ap_Get_Altitude"]));
            }
            set {
                this["ap_Get_Altitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+A")]
        public string ap_Set_Altitude {
            get {
                return ((string)(this["ap_Set_Altitude"]));
            }
            set {
                this["ap_Set_Altitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OemOpenBrackets")]
        public string ap_Command_Key {
            get {
                return ((string)(this["ap_Command_Key"]));
            }
            set {
                this["ap_Command_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public string ap_Get_Heading {
            get {
                return ((string)(this["ap_Get_Heading"]));
            }
            set {
                this["ap_Get_Heading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+H")]
        public string ap_Set_Heading {
            get {
                return ((string)(this["ap_Set_Heading"]));
            }
            set {
                this["ap_Set_Heading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string ap_Get_Airspeed {
            get {
                return ((string)(this["ap_Get_Airspeed"]));
            }
            set {
                this["ap_Get_Airspeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+S")]
        public string ap_Set_Airspeed {
            get {
                return ((string)(this["ap_Set_Airspeed"]));
            }
            set {
                this["ap_Set_Airspeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string Read_Flaps_Angle {
            get {
                return ((string)(this["Read_Flaps_Angle"]));
            }
            set {
                this["Read_Flaps_Angle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string ap_Get_Mach_Speed {
            get {
                return ((string)(this["ap_Get_Mach_Speed"]));
            }
            set {
                this["ap_Get_Mach_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+M")]
        public string ap_Set_Mach_Speed {
            get {
                return ((string)(this["ap_Set_Mach_Speed"]));
            }
            set {
                this["ap_Set_Mach_Speed"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public string ap_Get_Vertical_Speed {
            get {
                return ((string)(this["ap_Get_Vertical_Speed"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+V")]
        public string ap_Set_Vertical_Speed {
            get {
                return ((string)(this["ap_Set_Vertical_Speed"]));
            }
            set {
                this["ap_Set_Vertical_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string ap_Get_Com_Radios {
            get {
                return ((string)(this["ap_Get_Com_Radios"]));
            }
            set {
                this["ap_Get_Com_Radios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+C")]
        public string ap_Set_Com_Radios {
            get {
                return ((string)(this["ap_Set_Com_Radios"]));
            }
            set {
                this["ap_Set_Com_Radios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string ap_Get_Nav_Radios {
            get {
                return ((string)(this["ap_Get_Nav_Radios"]));
            }
            set {
                this["ap_Get_Nav_Radios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+N")]
        public string ap_Set_Nav_Radios {
            get {
                return ((string)(this["ap_Set_Nav_Radios"]));
            }
            set {
                this["ap_Set_Nav_Radios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string ap_Get_Transponder {
            get {
                return ((string)(this["ap_Get_Transponder"]));
            }
            set {
                this["ap_Get_Transponder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+T")]
        public string ap_Set_Transponder {
            get {
                return ((string)(this["ap_Set_Transponder"]));
            }
            set {
                this["ap_Set_Transponder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+F")]
        public string Fuel_Manager {
            get {
                return ((string)(this["Fuel_Manager"]));
            }
            set {
                this["Fuel_Manager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+S")]
        public string Output_History {
            get {
                return ((string)(this["Output_History"]));
            }
            set {
                this["Output_History"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+E")]
        public string Read_Landing_Gear {
            get {
                return ((string)(this["Read_Landing_Gear"]));
            }
            set {
                this["Read_Landing_Gear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+R")]
        public string ap_Set_Throttle {
            get {
                return ((string)(this["ap_Set_Throttle"]));
            }
            set {
                this["ap_Set_Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+A")]
        public string takeoff_assist {
            get {
                return ((string)(this["takeoff_assist"]));
            }
            set {
                this["takeoff_assist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+P")]
        public string flight_planner {
            get {
                return ((string)(this["flight_planner"]));
            }
            set {
                this["flight_planner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+P")]
        public string ap_PMDG_Panels {
            get {
                return ((string)(this["ap_PMDG_Panels"]));
            }
            set {
                this["ap_PMDG_Panels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+C")]
        public string ap_PMDG_CDU {
            get {
                return ((string)(this["ap_PMDG_CDU"]));
            }
            set {
                this["ap_PMDG_CDU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+V")]
        public string Landing_Rate {
            get {
                return ((string)(this["Landing_Rate"]));
            }
            set {
                this["Landing_Rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string ap_Get_Altimeter {
            get {
                return ((string)(this["ap_Get_Altimeter"]));
            }
            set {
                this["ap_Get_Altimeter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+B")]
        public string ap_Set_Altimeter {
            get {
                return ((string)(this["ap_Set_Altimeter"]));
            }
            set {
                this["ap_Set_Altimeter"] = value;
            }
        }
    }
}
